dist: trusty
os: linux

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm cache clean
  - rm -rf node_modules
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_script:
  - npm run coveralls
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
